src/theme/index.css
src/theme/responsive-image.css

This is a very minimal way of supporting responsive images. I don't think we should any more than this though.
The [specs in JIRA](https://jira.dhis2.org/browse/TECH-76) also mentions something about supporting high-resolution images (but Joe also wasn't sure about this). I think this is out-of-scope because any solution for this would require different images on the server for different resolution depths.

Responsive images

---

package.json
yarn.lock

Add support for pre-commit hooks e.g. auto-format code before it get's committed.

pre-commit hooks: `yarn format` code before commit

---

src/utils/defer.js

remove un-used file, defer func. already in utils/timings.js

remove un-used file, defer func. already in utils/timings.js

---

example-app/src/App.js
example-app/src/index.js
src/core/Menu/SubMenu.js
src/core/Popover/computePosition.js
src/utils/rtl.js

- set document direction doesn't need to know about API structure
- use getDoc() from html to get consistent behavior across UI

refactor(RTL)

---

example-app/src/App.js
example-app/src/ButtonDemo.js
example-app/src/LogoDemo.js
package.json
postcss.config.js
src/core/Button/Button.js
src/core/Button/styles.css
src/core/Logo/index.js
src/core/Logo/styles.css
src/core/Paper/index.js
src/core/Paper/styles.css
src/core/UI/index.js
src/utils/css.js

https://github.com/css-modules/css-modules
https://github.com/css-modules/postcss-modules
All CSS has local scope (`:local`) by default but global scopes are possible (`:global`).
```
/* composing classes */ 
.otherClassName {
composes: className from "./style.css";
}
.otherClassNameGlobal {
composes: globalClassName from global;
}
```

Introduce postcss-modules

---

src/core/CircularProgress/index.js
src/core/Icon/index.js

- CircularProgress: Separate out SVG Icon
semanatic rename progressBar to view as it's a CircularProgress
- Icon
use undefined for onClick
use correct syntax to refer to className

CircularProgress, Icon

---

README.md
src/core/Tabs/Tabs.js
yarn.lock

- purge useless documentation
- remove invalid file reference in Tabs.js

style: README.md, Tabs.js

---

src/utils/css.js

I didn't find any usage for `remove bemClassNames` in code.

remove bemClassNames

---

src/core/Icon/index.js
src/utils/theme.js

- reject undefined args
- accept only valid string, number or boolean(true)

refactor(t-func)

---

src/core/Dialog/index.js
src/core/Menu/MenuItem.js
src/core/Menu/PopoverMenu.js
src/core/Menu/SubMenu.js
src/core/Popover/index.js

**Refactor**
- simplify exports
- simplify logic in some places by placing code in context
- only offer direct element references for anchor element
- rename positionStyle -> style, attachPointPropType -> positionType

refactor(Popover)

---

docs/src/demos/Organisms/HeaderBar/index.js
docs/yarn.lock
package.json
src/core/Menu/MenuItem.js
src/core/Menu/styles.css
src/core/index.js
src/widgets/HeaderBar/HeaderBar.Component.js
src/widgets/HeaderBar/HeaderBar.Container.js
src/widgets/HeaderBar/Profile.js
src/widgets/HeaderBar/styles.css
yarn.lock

- Rename property selection to status in HeaderBar
- Use built-in core components to generate User Profile popup
- Attach default props to menu so it can be used independently from Menu
- Set correct color for menu Icon

fixes(headerbar)

---

docs/src/demos/Organisms/HeaderBar/index.js
src/widgets/HeaderBar/HeaderBar.Component.js
src/widgets/HeaderBar/Profile.js
src/widgets/HeaderBar/styles.css

- add _instanceName_, _appName_ props
- open **Profile** _onClick_
- remove _status_ prop
- remove _transparent_, _white_ theme
- update Demo

feat(headerbar) fixes / updates

---

src/core/InputField/index.js
src/core/helpers/Label/styles.css

`kind: outline`
- fix CSS for border-bottom (left/right) radius
- fix CSS border-width

style(InputField)

---

src/core/InputField/styles.css
src/core/SelectField/index.js
src/core/SelectField/styles.css

- prevent onClick, onToggle events
- correct CSS color for disabled dropdown-icon

fix(SelectField): prevent disabled field issues

---

docs/src/demos/Organisms/HeaderBar/index.js
src/utils/index.js
src/utils/url.js
src/widgets/HeaderBar/Apps.js
src/widgets/HeaderBar/HeaderBar.Component.js
src/widgets/HeaderBar/Profile.js
src/widgets/HeaderBar/styles.css

- use `core/InputField`, remove `core/Input/TextField`
- sort CSS props
- add helper func. `gotoURL` to prevent using `window.location` directly
- correct `baseURL` path for `HeaderbarDemo`

style(headerbar): use InputField

---

docs/src/App.css
docs/src/index.css
docs/src/index.js
src/core/UI/base/typography.css

- remove index.css. App.css contains the related code
- set default fonts for LTR and RTL

style(UI): set default fonts for LTR, RTL

---

src/core/UI/base/typography.css
src/utils/api.js

for dev. environment `url` and `endpoint` is undefined.

fix(api): url, endpoint is undefined in dev. environments

---

docs/package.json
src/widgets/HeaderBar/Apps.js

- Start docs app on port 5000
- Fix func. scope for `removeEventListener` in _HeaderBar/Apps_  `componentWillMount` to `componentWillUnmount`

minor fixes

---

src/core/InputField/index.js
src/core/Switch/styles.css

fix(input): do not allow disabled inputs to focus
style(switch): keep same color when toggling in error/warning states

minor bug fixes

---

docs/src/demos/Organisms/HeaderBar/index.js
src/core/Card/styles.css
src/core/InputField/index.js
src/core/InputField/styles.css
src/core/SelectField/index.js
src/core/SelectField/styles.css
src/defaults/colors.css
src/widgets/HeaderBar/Apps.js
src/widgets/HeaderBar/Profile.js
src/widgets/HeaderBar/styles.css

Got some feedback from @larshelge on the Headerbar and made adjustments accordingly.

Header bar fixes

---

README.md

docs: update references to code; remove bottom docs links

---

src/core/Button/index.js
src/core/Card/index.js
src/core/Checkbox/index.js
src/core/Chip/index.js
src/core/CircularProgress/index.js
src/core/Divider/index.js
src/core/DropdownButton/index.js
src/core/Help/index.js
src/core/Icon/index.js
src/core/InputField/index.js
src/core/LinearProgress/index.js
src/core/Logo/index.js
src/core/Menu/MenuItem.js
src/core/Menu/index.js
src/core/Menu/styles.js
src/core/Radio/index.js
src/core/SelectField/index.js
src/core/SplitButton/index.js
src/core/Switch/index.js
src/widgets/HeaderBar/HeaderBar.js

feat: add classname proptype to all components

---

src/Button/styles.js
src/Card/index.js
src/Checkbox/index.js
src/Checkbox/styles.js
src/Chip/styles.js
src/Help/index.js
src/Radio/index.js

* fix: adjust secondary button border style
* fix: increase primary button font weight, focus style
* fix: adjust card box shadow, border radius
* fix: adjust checkbox border color, label color
* fix: adjust selected chip font weight
* fix: adjust chip hover color
* fix: adjust help text state colors
* fix: adjust radio border color
No structural changes made, everything done in css so there should not be any issues (fingers crossed, my first DHIS2 PR...)

Minor styling changes to atoms

---

src/Button/styles.js
src/Chip/styles.js
src/Input/index.js
src/MenuItem/styles.js
src/SelectField/Select.js

* fix: base button style, text color updated
* fix: chip text color updated
* fix: input text color updated (all variations)
* fix: menu item text color updated, required an import of 'colors,theme' into MenuItem
* fix: select text color updated, requred import of 'colors'

fix: text color adjustments in multiple components

---

src/Help/index.js

ref. [#183](https://github.com/dhis2/ui-core/pull/183#issuecomment-489029923)

fix: use 16 px indentation for help component

---

src/Menu/index.js
src/MenuItem/styles.js

fix: adjust dense menu padding
fix: adjust padding on main menu block
fix: adjust menu item hover color

fix: adjust menu styling

---

src/FieldLabel/Filled/Label.js
src/FieldLabel/Filled/index.js
src/FieldLabel/Outlined/Label.js
src/FieldLabel/Outlined/index.js
stories/InputField.stories.js

fix(input field and select field): crop long labels

---

README.md

docs: document gotcha for global rules bleeding into components

---

.storybook/config.js
.storybook/preview-head.html
.storybook/reset-decorator.js
src/CssReset/index.js
stories/CssReset.stories.js

fix: add font-family to everything

---

src/ComponentCover/index.js
src/DropMenu/index.js
src/FieldLabel/Filled/index.js
src/ScreenCover/index.js
src/theme.js

Based on: https://github.com/dhis2/design-system/blob/master/principles/spacing-alignment.md#stacking

fix: introduce the stacking context

---

src/ComponentCover/index.js
src/MenuItem/styles.js
src/ScreenCover/index.js

fix: color/opacity of ScreenCover
fix: color/opacity of ComponentCover
fix: added padding-right to menu labels, space needed between label and right arrow

fix: styling adjustments

---

src/MenuItem/styles.js

fix(menu item): differentiate between hover and active style

---

src/Table/TableCell.js
src/Table/TableCellText.js
src/Table/TableRow.js

fix: remove space, extra borders between table cells <400
fix: adjust spacing/padding tables cells <400

fix: <400 table styles 

---

src/Button/index.js
stories/Button.stories.js

Adds the functionality to give focus to a button initially.

feat: add focus prop to button

---

src/Tabs/ScrollBar.js
src/Tabs/TabBar.js

As per your advice, I sprinkled on some flex-grow: 1

fix(tabs): apply flex-grow to ScrollBar and TabBar

---

.travis.yml

We are moving the docs to Netlify: https://core.ui.dhis2.nu/

chore: remove deploy-build to d2-ci

---

.eslintrc.js

Following Viktor's recommendation here https://github.com/dhis2/ui-core/pull/438#discussion_r326851557

chore(eslint): use fixed react version 16.3

---

src/RadioGroup/index.js
stories/RadioGroup.stories.js

fix(radiogroup): make the label optional

---

cypress.json

Enables Cypress dashboards for UI-core

ci: setup cypress project id

---

src/Input.js

feat(input atom): add ellipsis to overflowing text

---

src/Input.js
src/InputField.js

See https://github.com/dhis2/ui-core/issues/492 for allowed types

fix(input): allow types specified in design-system

---

src/Field.js
src/Label.js
src/Modal.js
src/Node.js
src/Tabs/ScrollBar.js
src/Tabs/Tab.js
src/Tabs/TabBar.js

I've added the className props to the following components:
* Node
* Field
* Label
* Modal
* Tabs components
<hr />
I also fixed some incorrect/missing jsdocs

feat: add className props to all components

---

src/MultiSelect/FilterableMenu.js
src/Select/FilterableMenu.js
src/SingleSelect/FilterableMenu.js

This one slipped by, I noticed whilst working on the new callback approach.

fix: correct handler usage for filterable menu

---

stories/info/molecules/alertBar.md
stories/info/molecules/tabs.md

docs: fixed image links on AlertBar and Tabs info section on Storybook

---

src/Select/FilterableMenu.js

Makes filtering case insensitive.

fix(select): make filtering case insensitive

---

src/Select/InputWrapper.js
stories/MultiSelect.stories.js
stories/MultiSelectField.stories.js
stories/SingleSelect.stories.js
stories/SingleSelectField.stories.js

The default for the tabindex was missing.

fix(select): add missing tab index default

---

src/AlertStack.js
src/DropMenu.js
src/LayerContext.js
src/ScreenCover.js
src/Select/MenuWrapper.js
stories/Modal.stories.js

Something went wrong whilst rebasing the original branch and it was much easier to start a new branch than to try and correct what had gone wrong in the other. The discussion may still be relevant and can be found here #572

fix: introduce layer-context to deal with overlapping elements + story

---

src/Backdrop.js
src/ScreenCover.js
src/Select.js
src/Select/MenuWrapper.js
stories/ScreenCover.stories.js

This needs @HendrikThePendric's PR (https://github.com/dhis2/ui-core/pull/582) in order to work properly. But with that (and thus the correct z-indexes), it works as expected. Plus it gets rid of the global click listener, which is nice.

fix(select): fix select closing on chip removal

---

src/Select.js

Our use of the backdrop as a parent for the menu means that the first positioned parent of the menu is now the backdrop. Since the backdrop is positioned fixed to the viewport, we need to change the measurement strategy, as now the menu will effectively be positioned relative to the viewport as well.
Since we're now positioning relative to the viewport we need to do a little more manual work in positioning the menu (previously the browser would do this for us, as we'd just supply the position relative to the document).
So I've adapted the measurement to be relative to the viewport, and am remeasuring on scroll. Eventually it would be nice to delegate this all to the browser again, as the current solution has a lot more potential for janky rendering because it's done in js.
I've also …

fix(select): fix positioning issues

---

src/Constrictor.js
src/Input.js
src/InputField.js
src/MultiSelect.js
src/MultiSelectField.js
src/SingleSelect.js
src/SingleSelectField.js
src/TextAreaField.js
src/index.js
stories/MultiSelect.stories.js
stories/MultiSelectField.stories.js
stories/SingleSelect.stories.js
stories/SingleSelectField.stories.js
stories/TextArea.stories.js

This is one of two options discussed in the meeting: https://github.com/dhis2/notes/pull/83
Resolves #605

refactor: use a constrictor component to constrain components width

---

src/Backdrop.js
src/Button.js
src/Chip.js
src/Chip/Remove.js
src/Node.js
stories/Button.stories.js

Some notes:
- Backdrop: is not exposed itself but can still get an undefined onChange via ScreenCover
- Button: logger fn in story also had a bad signature
- Chip: had a regression that would make every chip deletable

fix: avoid unconditionally calling optional event handlers

---

src/MultiSelect/Input.js
src/SingleSelect/Input.js

Callback for the clear button hadn't been updated to the cb signature. This fixes that.

fix(select): fix clear button callback to use new callback signature

---

.github/workflows/cypress.yml
cypress.json
package.json

ci: run cypress on github actions

---

src/MultiSelect/Menu.js
src/MultiSelect/SelectionList.js
src/SingleSelect/Menu.js

This fixes two functions that were expecting the event as the first arg, instead of the second.
(Will be tested here: https://github.com/dhis2/ui-core/pull/627)

fix(select): update ignored click cb signature

---

cypress/integration/transfer/disabled-transfer-buttons.feature
cypress/integration/transfer/display-order.feature
cypress/integration/transfer/drag-and-drop-items.feature
cypress/integration/transfer/filter-options-list.feature
cypress/integration/transfer/highlight-items.feature
cypress/integration/transfer/reorder-with-buttons.feature
cypress/integration/transfer/transferring-items.feature

`.feature` files for the [Transfer](https://github.com/dhis2/design-system/blob/master/organisms/transfer.md) component.
I have tried to keep these feature files strictly functional. There is some repetition in some of the scenarios where two functionalities are very similar (e.g. reordering up or down) but I felt they should be tested independently. There are some comments throughout the files, please take a look and provide feedback.

feat: transfer feature files

---

cypress/integration/MultiSelect/Accepts_blur_cb.feature
cypress/integration/MultiSelect/Accepts_blur_cb/index.js
cypress/integration/MultiSelect/Accepts_focus_cb.feature
cypress/integration/MultiSelect/Accepts_focus_cb/index.js
cypress/integration/MultiSelect/Accepts_initial_focus/index.js
cypress/integration/MultiSelect/Can_be_opened_and_closed/index.js
cypress/integration/MultiSelect/common/index.js
cypress/integration/SingleSelect/Accepts_blur_cb.feature
cypress/integration/SingleSelect/Accepts_blur_cb/index.js
cypress/integration/SingleSelect/Accepts_focus_cb.feature
cypress/integration/SingleSelect/Accepts_focus_cb/index.js
cypress/integration/SingleSelect/Accepts_initial_focus/index.js
cypress/integration/SingleSelect/Can_be_opened_and_closed/index.js
cypress/integration/SingleSelect/common/index.js
stories/MultiSelect.stories.testing.js
stories/SingleSelect.stories.testing.js

Add the remaining tests for onFocus and onBlur for the Selects.

test(select): add onfocus and onblur tests

---

src/Chip/Icon.js
src/Chip/Remove.js

In https://github.com/dhis2/ui-core/pull/664 I missed that the child Remove component was also still a class. I also changed the if statements to include braces, for safety: https://eslint.org/docs/rules/curly
(Noticed this whilst going through the components for the data-test additions)

refactor(chip): simplify remove component

---

cypress/integration/Menu/position.feature
cypress/integration/Popover/position.feature
cypress/integration/Select/position.feature
cypress/integration/Tooltip/position.feature
cypress/integration/menu/position.feature
cypress/integration/popover/position.feature
cypress/integration/select-menu/position.feature
cypress/integration/tooltip/position.feature

I've made some changes to the 4 feature files for the components.
I tried to
* simplify the scenarios
* use more generic examples
* remove any design specific values / specs
Let me know what you think
(maybe it's good to compare side by side what I've changed)

chore: adjust sentences to fit a programmatic approach

---

src/FileInputField.js
src/FileList.js
src/Modal.js
src/Modal/ModalCard.js
src/ModalActions.js
src/TabBar.js
src/Table.js
src/TableBody.js
src/TableFoot.js
src/TableHead.js
src/TableRow.js
src/TableRowHead.js

As discussed here: https://dhis2.slack.com/archives/CBM8LNEQM/p1576547094025800

fix: relax prop-validation on children to prevent false positives

---

src/Select/MenuWrapper.js

Tiny fix, there was an incorrect data-test attribute on the menu wrapper div.

fix(select): fix incorrect data-test attribute

---

src/MultiSelectOption.js
src/SingleSelectOption.js

Optionally, we could also choose to go with `data-test-value` and `data-test-label`, to indicate that these attributes are intented to be used for testing?

feat(select): add data attributes for options

---

netlify.toml
package.json
yarn.lock

Forgot to remove the Babel dependencies when porting to the app-scripts.

chore(deps-dev): remove babel deps

---

cypress/integration/Node/Can_be_closed/index.js
cypress/integration/Node/Can_be_opened/index.js
src/Node.js
src/Node/Arrow.js
src/Node/Toggle.js

This will fix the currently failing cypress tests

fix: use "old" Node arrow icon & rename arrow to toggle

---

src/MenuItem.js

This is just a quick fix for https://github.com/dhis2/ui-core/issues/782. The Menu (incl. SubMenus) will get a proper refactor in another branch.

fix(menu): adjust selector for opening submenu

---

cypress/integration/MenuItem/Accepts_target.feature
cypress/integration/MenuItem/Accepts_target/index.js
src/MenuItem.js
src/__e2e__/MenuItem.stories.js

feat(menu item): add target prop

---

cypress/integration/Transfer/drag-and-drop-items.feature
cypress/integration/Transfer/highlight-items.feature
cypress/integration/Transfer/reorder-with-buttons.feature
cypress/integration/Transfer/transferring-items.feature

adjusted feature files to be written from the context, rather than the implications.
also took the opportunity to add some more detail to features that were lacking it.

fix: rewrite transfer feature files from user perspective, add missing details

---

src/Chip.js
src/Chip/Remove.js
src/__demo__/Chip.stories.js
src/icons/Cancel--outline.js

This PR makes additions and adjustments to the `Chip` component:
- added `dense` style
- adjusted remove icon to be less visually dominating

feat: chip adjustments

---

src/Popover.js
src/Popper.js
src/Popper/getReferenceElement.js
src/__demo__/Popper.stories.js
src/common-prop-types.js

This feature is needed to unblock some work that @edoardo is doing. I've included some stories that are demoing the functionality, but no e2e tests. I'd like to pick that up later, once this work has gone into `@dhis2/ui`.

feat: add support for virtual elements in popper and popover

---

src/MenuItem/MenuItemContent.js
src/__demo__/Menu.stories.js

Again, this PR would unblock some work that @edoardo is doing

fix: prevent icon from shrinking when label text overflows
