package.json
src/App.js
src/packages/Button/Button.js
src/packages/Button/button.css
src/packages/CircularProgress/CircularProgress.js
src/packages/CircularProgress/circular-progress.css
src/packages/LinearProgress/LinearProgress.js
src/packages/LinearProgress/linear-progress.css
src/packages/Logo/Logo.js
src/packages/Paper/Paper.js
src/packages/Paper/paper.css
src/packages/Popover/Popover.js
src/packages/Popover/popover.css
src/utils/bemClassNames.js
src/utils/index.js
yarn.lock

When reviewing, I think the most important file would be `src/utils/bemClassNames.js` which contains the actual implementation of the `bemClassNames` utility function. The idea is like this:
- `bemClassNames` is a closure. You call it outside of the component with the block/component name and store the returned function in a variable (called bem for convention).
- Then, in the component call the returned function with as many parameters as you like.
- The first parameter is used as an `element` (as in block__element). This is also why you must call `bem(null, 'modifier');` if you want to add a modifier to the block class.
- The subsequent parameters are used to build modifiers. The HTML element will end up with `nrOfModifiers + 1` classes attached to it: 1 for the base block_element class …

Implement bem methodology

---

example-app/src/index.js
src/utils/index.js
src/utils/setDirAndThemeAttributes.js

This is more of a proof of concept than anything else, based on our discussion we had yesterday regarding the `isRtl()` utility function which is currently broken. What I propose is the following:
- This function would run BEFORE the app is rendered into the DOM to ensure that the HTML attribute and body class are have been set. (see `example-app/src/index.js`)
- It would fit nicely into a "bootstrap-sequence" as we have in most DHIS2 apps. (See example in the JSDoc comment in `src/utils/setDirAndThemeAttributes.js`)
- This fixes the `isRtl` function. And this removes the need for any context / lifecycle methods / element ref in our React components.
What I don't like:
1. The fact that we are using a lookup for RTL languages. However, I discussed this with Adeel and he had some compelling …

Dir and theme helper

---

package.json

chore(package): update postcss-nested to version 4.1.0

---

src/Tabs/TabIndicator.js
src/Tabs/Tabs.js
src/Tabs/computeHorizontalScrollbarHeight.js
src/Tabs/tabindicator.css
src/Tabs/tabs.css

This includes a couple of fixes:
- **All browsers**: Compute horizontal scrollbar height instead of assuming this is 15px in all browser/OS combos, which is not true.
- **Edge**: tab-indicator lifts up 2px whilst moving, showing whitespace below. Now moved the indicator 2 px down and increased height by 2px. This looks a lot better in Edge, and the same in all other browsers
- **FF52**: tabs would take up several lines instead of being forced into one. Found out that the `width: -moz-max-content;` fixes this.

Tabs compute scrollbar height

---

src/utils/html.js

- documentation
- rename children to nodes, cud have been textNodes but nodes is
shorter. This separates the word children from React.Children

style(wrapTextNodesInSpans)

---

example-app/src/ButtonDemo.js
src/core/Button/DropdownButton.js
src/core/Menu/MenuItem.js
src/utils/html.js

- fix className reference in dropdownButton
- remove wrapTextNodesInSpans reference

DropdownButton

---

example-app/src/DialogDemo.js
src/core/Dialog/index.js
src/widgets/HeaderBar/Apps.js

**Updates**
- use Dialog children for content rather then prop. Helps developers
layout content inside the render func. or where ever Dialog is used
- replace actions with an Array to simplify Button render logic
- rename events to onClose
**Issue**
`Dialog/index.js` not sure about the last 3 lines. withAnimatedClose get's applied twice to _EnhancedDialog_
```js
const EnhancedDialog = withAnimatedClose(Dialog)
export { EnhancedDialog as Dialog }
export default withAnimatedClose(EnhancedDialog)
```

refactor(Dialog)

---

example-app/src/App.js
example-app/src/ButtonDemo.js
example-app/src/HeaderBarDemo.js
src/core/Button/DropdownButton.js
src/core/Input/SelectField/index.js
src/core/Menu/DropdownMenu.js
src/core/Menu/Menu.js
src/core/Menu/MenuItem.js
src/core/Menu/PopoverMenu.js
src/core/Menu/SubMenu.js
src/core/Popover/index.js
src/widgets/HeaderBar/Apps.js

Refactored code to be more readable for DropdownMenu
- simplify property passing
- naming changes for events and component
*SubMenu.js*
Children is not used in PopoverMenu. MenuItems should just be a list of items passed in as `list={list}` prop.
Line 29-32
```js
const menuProps = isValidElement(menuItems[0])
? { children: menuItems }
: { options: menuItems }
```

refactor(DropdownButton)

---

package.json

I added a hook called [`commit-style`](https://github.com/dhis2/code-style/blob/master/commit-style) to the **code-style** package, so we can get conventional commits going.
This allows us to generate changelogs: https://github.com/conventional-changelog/conventional-changelog

Add message hook to husky

---

src/core/UI/theme/blue.css

we should better identify the target use-case in destination, as this over-ride will add un-necessary background to all `<a/>` tags on focus/click

fix(style-overrides)

---

src/widgets/HeaderBar/styles.css

- On Maps app Bjorn has set 1000 z-index on the map container which hides our **profile** and **apps** dropdown
- Settings **10,000** for the z-index is probably reasonable enough to overcome any z-index issues we find during `<HeaderBar />` integrations

fix(headerbar style): fix z-index on apps/profile dropdown

---

src/widgets/HeaderBar/HeaderBar.Container.js

There was already some code for displaying the user-avatar if the profile had a truthy `img` property. However, this property was not being plucked of the API response. I think this was because the avatar wasn't really supported via the API when Adeel worked on this.

fix(headerbar): display avatar img

---

README.md

Maybe I'm missing something, but having a link to create-react-app docs here seems wrong.  Updating to point at the gh-pages publication, but maybe this section is not needed since that page is liked from the top of the readme?

docs: link to dhis2/ui docs instead of create-react-app

---

package.json

.mjs triggers webpack 4 to load with strict-ESM rules, which isn't part
of any spec yet from what I can find out[1].
[1] https://medium.com/webpack/webpack-4-import-and-commonjs-d619d626b655

fix: use .es.js extension over .mjs at this point

---

src/defaults/reset.css

@joakimia pointed out that the some of the resets might be a bit too aggressive. Specifically, the rule `font: inherit;` has some big consequences, it touches the following font-related styles:
```css
font-style: inherit; /* this is a problem for <i> and <em> */
font-variant-ligatures: inherit;
font-variant-caps: inherit;
font-variant-numeric: inherit;
font-variant-east-asian: inherit;
font-weight: inherit; /* this is a problem for <b> and <strong> */
font-stretch: inherit;
font-size: 100%;
line-height: inherit;
font-family: inherit;
```
I've added two additional rules to address these issues.

fix(reset): b and strong should be bold and i and em italic

---

src/Button/index.js
src/DropMenu/getPosition.js
src/DropMenu/index.js
src/DropdownButton/index.js
src/SplitButton/index.js

This PR ties in to the comment I made here https://github.com/dhis2/ui-core/pull/183#pullrequestreview-224460229:
> SplitButton and DropDownButton use a very simple div with position absolute to render stuff into a “Popover-menu”. This approach is fragile: there are going to be situations where the menu isn’t rendered fully if the container has overflow-y hidden, and also potential z-index problems if parents also have certain z-index properties (a child's z-index is set to the same stacking index as its parent). It would be better to render stuff in a portal (React.createPortal) as the last child of the document body. Stuff does become more complex this way because the position will have to be computed, but it will be more robust.
Based on this comment, the DropMenu was created, which …

feat(drop-menu): compute position relative to anchor element

---

src/Button/index.js
src/Checkbox/Input.js
src/Checkbox/index.js
src/Chip/index.js
src/Chip/styles.js
src/InputField/index.js
src/MenuItem/index.js
src/Radio/index.js
src/SelectField/Select.js
src/SelectField/index.js
src/SplitButton/index.js
src/Switch/index.js
stories/Button.stories.js
stories/Checkbox.stories.js
stories/Chip.stories.js
stories/DropdownButton.stories.js
stories/InputField.stories.js
stories/Menu.stories.js
stories/Radio.stories.js
stories/SelectField.stories.js
stories/SplitButton.stories.js
stories/Switch.stories.js

The Switch, Checkbox, and Radio could easily be converted to functional components just based on props, which is nice.

refactor: make fields controlled

---

src/FieldLabel/Filled/index.js
src/FieldLabel/Outlined/index.js
src/InputField/index.js

Now passing the `className` prop down to the `Container`, which can be either the `Filled` or the `Outlined` `FieldLabel`

fix(input-field): add className to container

---

src/FieldLabel/Filled/Label.js
src/FieldLabel/Outlined/Label.js
stories/InputField.stories.js
stories/SelectField.stories.js

Added required star for Outlined SelectField and InputField

fix: required star

---

src/CircularProgress/index.js
src/ComponentCover/index.js
src/LinearProgress/index.js
src/LinearProgress/styles.js
src/Modal/index.js
src/ScreenCover/index.js
src/index.js
stories/CircularProgress.stories.js
stories/ComponentCover.stories.js
stories/LinearProgress.stories.js
stories/ScreenCover.stories.js

Adds a Portal to the Overlay so its always rendered on top of the other components.
Removes the "overlay a single component" for now. It's not used anywhere and the app can easily build this using the component as is.
Fixes #217.

feat: use a portal to overlay the loader

---

src/DropMenu/index.js

Gatsby throws an error if it encounters `Element` during build time. I realize that Gatsby-compliance probably isn't highly prioritized, but this should be a change of little consequence.

fix: issue with gatsby

---

.storybook/config.js
.storybook/css-reset-decorator.js
.storybook/frame-styles-decorator.js

This PR
* removes the unnecessary div around the story contents
* Add the spacing to #root
* replaces the margin with padding (so there can't be collapsing margin)
* Set's the html/body height to use at least the viewport space (so stories can use `height: 100%`)

refactor: style frame instead & set body to full height

---

src/Checkbox/Icon.js
src/Checkbox/Label.js
src/Checkbox/index.js
src/Radio/index.js
src/Radio/styles.js
stories/Checkbox.stories.js
stories/Radio.stories.js

Add the `icon` prop to both the `Checkbox` and the `Radio` components to allow icons between the input icon and the label text.
Also splits the margin of the label text of both components into paddings on the input icon and the label text to ensure there's always 8px of empty space between the input icon and the label text, regardless whether there's a custom icon or not.

feat(checkbox & radio): add custom icon prop

---

package.json
yarn.lock

Tested all of them together (works) and resolved merge conflicts for safer merge into master
chore(deps-dev): bump @babel/plugin-transform-react-constant-elements
chore(deps-dev): bump @babel/plugin-proposal-object-rest-spread
chore(deps-dev): bump @babel/cli from 7.4.4 to 7.5.0
chore(deps-dev): bump @babel/plugin-proposal-class-properties
chore(deps-dev): bump @babel/preset-env from 7.4.5 to 7.5.0
chore(deps-dev): bump @babel/core from 7.4.5 to 7.5.0

chore(dev-deps): bump babel dependencies to 7.5.0

---

stories/Tabs.stories.js

Removed the interactive example because this was mainly used during development, and doesn't gives a very good JSX illustration of how to use this component.

chore(tabs): remove interactive storybook dev example

---

src/Tabs/Tab.js
src/Tabs/TabBar.js

Previous to this fix, the `line-height` of the `<Tab />`s was equal to the `font-size`.
This caused letters like `g` to be cut-off due to `overflow: hidden`

fix(tab): increase line-height & decrease padding to preserve height

---

src/Table/Table.js
src/Table/TableBody.js
src/Table/TableCell.js
src/Table/TableCellHead.js
src/Table/TableCellText.js
src/Table/TableFoot.js
src/Table/TableHead.js
src/Table/TableRow.js
src/Table/TableRowHead.js
src/Table/extractHeaderLabels.js
src/Table/index.js
stories/Table.stories.js

With these changes, the title for all table cells has to be provided to the table head cells.
They're extracted by leveraging the `React.Children` api, coupled with stricter propTypes to ensure that only the correct components are used.
I've decided against using a config object because it was way harder to read. Now the table can be constructed like a normal table, with multiple rows in the `thead`.
The `TableCell` component has a `noTitle` prop if the content is special and doesn't need a title.
I've added examples in the storybook
UPDATE:
I could use the same approach for row-header labels (the vertical headers displayed in pivot tables for example)

Table header labels in context

---

src/MenuItem/index.js
src/MenuItem/styles.js
src/Switch/styles.js

With this change the navigation will be semantically correct, rendering `a` elements when there's either a `href` or an `onClick` callback.
Said element will be a `span` when neither if given (i. e. so a `Switch` can be renderen inside a `MenuItem`)
This PR will also add a height value to the `Switch` so it's not cut off anymore when inside elements with `overflow: hidden` (see current `Menu > Default` storybook demo)

feat: wrap contents with a link element when href or onClick is given

---

src/Checkbox/Label.js
src/Checkbox/index.js
src/Radio/index.js
src/theme.js

Fixes dhis2/design-system#6
This PR will change the theme's `disabled` color from `grey500` to `grey600`,
which will impact all components that are using `colors.disabled` of the theme.

fix: use correct disabled style & fix checkbox and radio disabled style

---

src/Help/index.js
stories/Help.stories.js

- use margin instead of padding so the correct space is reserved by a parent with `box-sizing: border-box`
- add `indent` property to toggle `margin-left` from `0` (false) to `dp16` (true | default)

fix(help): spacing

---

src/ButtonStrip/index.js
src/ButtonStrip/styles.js
src/SplitButton/index.js
stories/ButtonStrip.stories.js

BREAKING CHANGE: Removes the `compact` prop and styles from the ButtonStrip.

refactor: remove compact from button strip

---

src/Table/TableCell.js
src/Table/TableCellHead.js
src/Table/TableRow.js
stories/Table.stories.js

Main goal with this PR is to add the `dense` prop to the cells and rows of the static table (or show what I meant with it at least).
Another small change is that instead of using a `div` to set a `min-height` on the table-cell, this sets a `height` on the table-cell. Which effectively does the same as the cell can still grow larger in height, and it doesn't require an extra element. This way we don't need the global styles.
I've also removed the `min-height` settings from the table row, as they were overriding the table cell heights (when set to `height`). We could put it back in the same manner as the cells (with a `height` instead of `min-height`, and a `dense` prop), but that does mean that setting `dense` on the row will override the cells, which might be confusing.
Btw. I marked my …

feat: add dense prop to static table

---

src/Checkbox.js
src/Checkbox/Input.js
src/Radio.js

I believe that the `value` attribute on a checkbox element is not mandatory, so the corresponding prop on our component shouldn't be either.
Source:
> If the value attribute was omitted, the default value for the checkbox is on , so the submitted data in that case would be subscribe=on.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Value

fix: checkbox value should be optional

---

.travis.yml
src/Button.js
src/Checkbox/Label.js
src/Chip/Content.js
src/InputField.js
src/MenuList.js
src/Node.js
src/icons/Upload.js
stories/CssReset.stories.js
stories/CssVariables.stories.js
stories/Logo.stories.js
stories/Node.stories.js
stories/Switch.stories.js

One thing I noticed whilst going through the propType warnings that I didn't address yet:
It seems Input and Select have a `focus` prop, but the components are reporting receiving a function instead of a bool. In the Field story I'm not seeing a function being passed in for `focus` to the rendered Input component explicitly, so I'm not sure what's going on here exactly.
I looked at this with Hendrik, but we didn't have enough time to really figure out what was going wrong. It does seem like there's some funky stuff going on here. Input has an initialFocus prop as well for example (and uses it), and InputField defines one, but doesn't use it anywhere.
Wwe should enable react/no-unused-prop-types, to catch these kinds of things:
Some false positives, but might be useful

ci: lint source on ci as well

---

src/Input.js
src/InputField.js
stories/InputField.stories.js

- Removed `focus` prop
- Adjusted behaviour to respond to `initialFocus`
- Adjusted story with incorrect description of the actual behavior
- Removed abbreviation from other story

fix(input-field): adjust focus props and label story

---

.eslintrc.js
src/CssVariables.js

The thinking behind this is:
1. Because we now loop through the object keys of `allowedKeys` we prevent nasty errors
1. Since the previous change cause things to fail silently (i.e. developer adds prop `shape` which isn't in the `allowedKeys` so it's simply ignored), I added some props-validation that would let the developer know he has added a not-allowed prop.
Currently this PR has draft status because it is dependent on https://github.com/dhis2/prop-types/pull/46. Once that's been merged, we still need to update the version of `@dhis2/prop-types` here....

fix(css-variables): improve robustness and developer warnings

---

.eslintrc.js
.travis.yml
package.json
src/CssVariables.js
src/FileInput.js
src/Input.js
src/Label.js
src/SelectField.js
src/Tabs/Tab.js

We have a couple of components with props that aren't used. I've added a linting rule to catch this in the future and fixed some of the linting errors. However, for some of the linting errors I'm not sure if the props can be safely removed, or if this is a mistake and we actually want to use these props:
So @Mohammer5, @HendrikThePendric can the above props be safely removed?

ci: add no unused props rule

---

src/Table.js
src/index.js

Using dynamic re-exports prevents static bundlers (like rollup) from supporting CJS named imports - if we include the named exports explicitly instead, static named imports work in CJS modules.  
See [this app-platform issue](https://github.com/dhis2/app-platform/issues/69), [the app-platform rollup config](https://github.com/dhis2/app-platform/blob/master/cli/config/rollup.config.js#L77), and [the underlying rollup explanation](https://github.com/rollup/rollup-plugin-commonjs/issues/211#issuecomment-337897124) (which explains why this affects rollup but not webpack).
We should figure out how to support ES imports in rollup (maybe stop using rollup at all?) but for now this will make it a little less confusing when trying to do CJS named imports from `ui-core`

fix: don't use dynamic re-exports

---

src/Input.js
src/InputField.js
stories/InputField.stories.js

The following changes have been implemented:
- Showing the status icon next to the input
- Applying status styling directly on the input element
- Remove the `focus` state property and use the `:focus` selector instead
- Simplify CSS and remove redundant rules
- Add `readOnly` prop, styles, and story
- Add `width` prop, styles and story
- Add docs to Input
Some things I intentionally left out:
- Adjust border-color for disabled style: we need confirmation about https://github.com/dhis2/design-system/issues/15 first
- Apply `labelWidth` or `width` props as mentioned in https://github.com/dhis2/ui-core/pull/456#issuecomment-536522531. I think we should keep these changes out-of-scope for now and introduce these props once we need inline labels.

refactor(input): update implementation of Input and InputField

---

stories/InputField.stories.js

- We had a duplicate. So I removed that
- The JSX example for the "Default" story was slightly ambitious, because `label` was explicitly set to `undefined`. So I changed that too

fix(input): remove duplicate story and improve "Default" story

---

src/SplitButton.js

I noticed a few redundant styles whilst working on the the closed PR https://github.com/dhis2/ui-core/pull/501. This PR removes them.

fix(split-button): remove unused styles

---

stories/InputField.stories.js

This just prevent a prop-type warning

fix(input-field): add required `onChange` prop to all stories

---

src/AlertBar.js
src/AlertBar/Icon.js
src/FileInput.js
src/Input.js
src/Select.js
src/TextArea.js
src/icons/Status.js

- Added `info` and `defaultTo` props to status-icon
- Rename `StatusIconNoDefault` to `StatusIcon`
- Let AlertBar/Icon use `StatusIcon` to simplify component code

refactor: alert bar and status icon

---

src/Chip/Remove.js

Fixes #418 
I couldn't test this through browserstack in Edge, for some reason it doesn't load any of my local stories.
Could some one else please confirm that this works in Edge?

fix(chip remove icon): fix position cross browser

---

src/DropMenu.js

I've inserted `@private` into both jsDocv blocks. Not sure if that is required... Feel free to remove one.

docs(drop-menu): mark jsDoc comments as private to keep out of docs

---

src/MultiSelect/Input.js
src/MultiSelect/Menu.js
src/MultiSelect/SelectionList.js
src/MultiSelectOption.js
src/Select/FilterableMenu.js
src/SingleSelect/Input.js
src/SingleSelect/Menu.js
src/SingleSelectOption.js
stories/MultiSelect.stories.js
stories/SingleSelect.stories.js

This aligns the Select components with the changes in callback style. Things that aren't done yet:
Currently onChange will be called with the new value for `selected`, and the event. But I understand that the intention is to use an object as the first argument. I wasn't sure what name we'd want to use there. Maybe just `selected`? Suggestions are welcome.
We have to choose what to support by default for the callback style we supply to the options. We supply a callback that expects just an event, so it could be passed to an element like so: `onClick={onClick}`. I've gone with keeping that style, and am handling the exception in our MultiSelect [here](https://github.com/dhis2/ui-core/pull/566/files#diff-30592b1d577759c4462fd708b2a517cbR30). The MultiSelect option is an exception because it …

fix(select): align select with callback style changes

---

src/Checkbox.js
src/Input.js
src/Radio.js
src/Switch.js
src/TextArea.js

This touches the following components:
- `Checkbox`
- `Input`
- `Radio`
- `Switch`
- `TextArea`
I have not worked on the `Select` because I know that @ismay is working on that.
Because I was going to do very similar things to a number of components, I asked @Mohammer5 to give some feedback on my initial commit. I'll try to summarise what was discussed, so we don't end up discussing the same things again:
- We tried various different implementations but decided to stick with the mechanism introduced in https://github.com/dhis2/ui-core/commit/86d3a4103a6c2145944b795fec7d85af9a8e2bd0, because that correctly extracts the shared functionality. An example of the "runner-up" approach  would be something like this:
```javascript
handleChange = e => this.handleEvent(props.onChange, e)
handleFocus …
```

fix: align focus and blur handlers with change handler

---

src/Select.js
src/Select/MenuWrapper.js

Since the select's input area can change size after a selection, we have to check the position of the menu after a selection. FF was not measuring properly when scheduling the measurement on menu open, so I'm now measuring on mount as well. That has the advantage of already having the correct position before menu open.

fix: adjust menu position after option selection

---

.dependabot/config.yml
package.json
yarn.lock

Related: #572 
This would make it easier to implement the z-index context provider in #572.
UI core overview seems to indicate that everywhere we use ui-core (atm) has hooks enabled: https://dhis2.vardevs.se/layoftheland.html
As such, this seems like a reasonable change for the `next` branch.
BREAKING CHANGE: Now requires React >= 16.8.

chore: upgrade react to support hooks

---

src/Select.js

We only have `selected` to call back with (no name or value), so that's the only thing I've included in the object. The same is done for the onChange cb (already done).

fix(select): align onfocus and onblur with other cbs

---

src/ScreenCover.js
stories/ScreenCover.stories.js

Add a transparent prop, so the screencover can be used to catch clicks, instead of using a click listener on the document.

feat(screencover): add transparent prop

---

src/MultiSelect.js
src/MultiSelect/Input.js
src/MultiSelectField.js
src/SingleSelect.js
src/SingleSelect/Input.js
src/SingleSelectField.js
stories/MultiSelect.stories.js
stories/SingleSelect.stories.js

Sets a default max-height on the input, to keep it from getting too big when there are a lot of selected options, or when a single select option contains a lot of text.
Can be overridden with `inputMaxHeight` prop.

feat(select): add input max height prop

---

README.md

The old docs link linked to an outdated version of the Storybook.

Updated docs link in README

---

src/SingleSelectOption.js

The single select option was truncated, but to align it with how the multiselect option is displayed, we're displaying it in full. Eventually it would be good to display a tooltip for truncated multi select chips in the input:

refactor(select): display single select option in full in menu

---

src/MultiSelect.js
src/SingleSelect.js

Closes #591
Max-width can be used to limit flex-basis, which seems like what we want here (see: https://gedd.ski/post/the-difference-between-width-and-flex-basis). Fixes the issue demonstrated in #591.

fix(select): fix overlap on specifying input width for flex children

---

src/LayerContext.js

I realise that this fix only addresses a hypothetical issue given our current component set, but since we are all quite deeply into this now, it might still be a good time to tackle this....
In the current implementation, the following could hypothetically go wrong:
1. User opens modal => context z-index = 3000
2. User opens hypothetical component with `layers.blocking` from the modal => this would get z-index 3001
3. Whilst the component in (2) is open, the user opens another hypothetical component with `layers.applicationTop` from the modal => this would get z-index 3001 too
And because the components from point 2 & 3 have an equal z-index, but 3 is appended to the body later, comp3 will now be on top of comp2. And this is incorrect because comp2 has a higher layer.
After this fix comp2 …

fix(layer-context): add support for preserving layer hierarchy in context

---

src/TextArea.js

Without this fix the TextArea will throw an infinite recursion error when `autoGrow` is set to true

fix(text-area): only set height when value changes

---

src/Modal.js

I'm wondering if we should remove the aside as well. Although technically correct, it causes the `ScreenCover` to be rendered inside it. I think so far it hasn't caused any problems, so we can also just leave it in there until it causes problem, but it'd be a breaking change as we're removing stuff someone potentially relies upon

feat(modal): do not render modal if open is falsy

---

cypress/integration/SingleSelect/opening_and_closing.feature
cypress/integration/SingleSelect/opening_and_closing/opening_and_closing.js
stories/SingleSelect.stories.testing.js

_note: this is based on next, but not necessarily to be merged in next. We can also merge it afterwards._
I was looking at implementing cypress integration tests for the Select and I found the existing naming strategy rather verbose. Personally I'd prefer a simpler, more terse naming strategy. And preferably with dashes instead of underscores (as dashes are more conventional in js codebases in my experience).
So more like this (this still uses underscores btw.):
Instead of the current:
With the proposed changes, when running it'll look like this:
and
That would be an improvement in my perspective. What does everyone else think?

test(select): add select integration tests

---

stories/Button.stories.js

The integration test was failing because of a missing onClick handler. This wasn't caught because we're not running on CI (which we should have soon if all goes well), but I also think that our using the stories for both documentation and testing is to blame. It's easy to want to update the docs and break a test.
We already have the option to separate out stories that are for testing, and stories that are for documentation by using a `.testing` prefix. I propose we move all stories that are used for testing to `<ComponentName>.testing.stories.js`, like we're already doing for a couple of components:
The .testing stories won't show up in the docs, and it signals clearly that those stories are for testing.

test: fix button integration test

---

cypress/fixtures/FileInput/file.md
cypress/fixtures/FileInput/file.txt
cypress/integration/FileInput/Accepts_multiple_files.feature
cypress/integration/FileInput/Accepts_multiple_files/index.js
cypress/integration/FileInput/Can_be_changed.feature
cypress/integration/FileInput/Can_be_changed/index.js
cypress/integration/FileInput/common/index.js
cypress/support/index.js
cypress/support/uploadFile.js
cypress/support/uploadFile/hexStringToByte.js
cypress/support/uploadMultipleFiles.js
cypress/support/uploadSingleFile.js
stories/FileInput.stories.js

@HendrikThePendric Please check if the second scenario in the `Accepts_multiple_files.feature` is how this component is supposed to work, or if selecting files after some have been selected, should override the existing ones

Add file input tests

---

cypress/support/visitStory.js
package.json
yarn.lock

Closes #645
The obvious downside, is that this adds an entire new dev dependency for one function. But on-balance I think this is better than reverse engineering what storybook is doing.

chore: use storybook helper for visiting stories in cypress

---

src/AlertBar.js
src/CheckboxField.js
src/CheckboxGroup.js
src/CheckboxGroupField.js
src/DropdownButton.js
src/MultiSelect/FilterableMenu.js
src/RadioGroup.js
src/RadioGroupField.js
src/SingleSelect/FilterableMenu.js
src/SplitButton.js
src/SwitchField.js
src/SwitchGroup.js
src/SwitchGroupField.js

refactor: pass props explicitly instead of spreading props

---

CHANGELOG.md

Tiny fix for a typo in the docs I noticed whilst preparing for the demo. I assume that these changes will persist and not be overwritten in our automated release process @varl?

docs(changelog): fix select callback object typo

---

src/Chip.js

Something I noticed whilst going through ui-core for another PR. This refactors the Chip to a function instead of class component (since it doesn't use state or anything that'd warrant a class). It uses an inline arrow function, which should be fine: https://cdb.reacttraining.com/react-inline-functions-and-performance-bdff784f5578. Just a sugggestion, seemed like an improvement to me, but let me know if I overlooked something.

refactor(chip): change chip to function component

---

src/ToggleGroup.js

This is a small refactor, to allow the data-test prop to be set correctly for the CheckboxGroup, RadioGroup and SwitchGroup. Without this fix, we can only set a data-test attribute on the children (as that's the only thing that ToggleGroup returns). With this fix, we can set it on the wrapper, which will look like this:

refactor(togglegroup): wrap children to allow for datatest attribute

---

src/TabBar.js
src/TabBar/Tabs.js

I've considered a couple different approaches to allow for a data-test attribute to be set on the TabBar. We've attached it to the root rendered node everywhere else, so that's my goal for the TabBar as well.
Initially I tried keeping the component as is. The existing markup is:
Keeping this as-is, means attaching the data-test attr. to either the Scrollable component, or a div wrapper (which would replace the current Fragment), depending on the value of `scrollable`. That would keep the markup reasonably similar, but I thought it made for a more confusing data-test attr. Because now, depending on the value of `scrollable`, the attribute is either attached to the scrollable component, or the root div. Which are different components, and at different points in the eventually rendered …

refactor(tabbar): add wrapper to allow for data-test

---

src/Modal.js
src/ModalActions.js
src/ModalContent.js
src/ModalTitle.js
stories/Modal.stories.js

To allow a Modal to be rendered with only content, we need to adjust the
margin/paddings on the components.
This also cleans up the dead prop `open` which was removed in v4.

feat(modal): allow modal without actions

---

src/Input.js

E.g. date from UA:
This adds additional types of input controls:
- date
- datetime
- datetime-local
- month
- week
- time
- search

feat(input): enable additional types on input

---

cypress/integration/Node/Can_be_closed/index.js
cypress/integration/Node/Can_be_opened/index.js
src/Node.js
src/Node/Arrow.js
src/Node/Contents.js
src/Node/Spacer.js

Follow-up of https://github.com/dhis2/ui-core/pull/676.
I've updated the rendering of the Arrow slightly, so that the intention of rendering either an Arrow or empty space is more obvious from the code. I've also updated classes, that seemed to be old style hooks, but seemed to be no longer used. Correct me if I'm wrong though.
The integration tests have to be updated, as they still target the classes. We could hold off on merging this until the data-test attrs. are in, rebase and then use them to fix the integration tests for this PR and merge this in.

refactor(node): add spacer component

---

src/CheckboxField.js
src/CheckboxGroup.js
src/CheckboxGroupField.js
src/DropdownButton.js
src/FileInputField.js
src/RadioGroup.js
src/RadioGroupField.js
src/SplitButton.js
src/SwitchField.js
src/SwitchGroup.js
src/SwitchGroupField.js
src/ToggleField.js
src/ToggleGroupField.js

Extracted the changes regarding the spreading of prop-types from https://github.com/dhis2/ui-core/pull/641, to clean that PR up.

refactor: set prop-types explicitly instead of spreading

---

src/Checkbox.js
src/Radio.js
src/Switch.js
src/ToggleGroup.js
src/ToggleGroup/Spacer.js

https://jira.dhis2.org/browse/TECH-272
Closes #669
The first solution (first commit) relied on things that can't be enforced, and seemed slightly brittle (the dense class to detect dense child components, relying on there always being a label in the child).
The second solution (second commit, current state of the PR), is a little less easy to parse, but properly separates ToggleGroup from it's children. Everything it needs is clearly indicated with proptypes, I prefer that as a solution.

refactor: move grouped styles to togglegroup component

---

src/Input.js
src/Select/InputWrapper.js

Some minor style changes to the `input` and `select` components.
I am changing the `min-height` defined for the `select`. I remember that this was discussed before and the current solution was the simplest. Right now there is a lack of consistency when using these types of user input side by side: 
With the changes in this PR, default sized select and input have the same height:
Are there any issues with these changes? [There was a slack discussion about this](https://dhis2.slack.com/archives/CBM8LNEQM/p1572261046057200), it looks like @Mohammer5 and @ismay had a call to discuss.
Ps. Are we merging straight into `master` now? I see there is no `next`. Please confirm before I merge 😉

fix: input and select styling

---

cypress/integration/Menu/position.feature
cypress/integration/Popover/position.feature
cypress/integration/Select/position.feature
cypress/integration/Tooltip/position.feature
cypress/integration/position-utility/positions.feature

First pass at specs for each component that requires positioning. A generic `position-options.feature` specs the available options/locations for positioning. This follows the [position utility discussion](https://github.com/dhis2/notes/blob/master/decisions/2019/10/15-popover-position.md).
@dhis2/team-apps, please add to and correct where necessary! I tried to keep the specs generic enough to apply to all situations, but with enough detail that they can actually be tested.
---
I have covered the components that definitely need the position utility. There are also some 'maybe' components. These can 'reuse' the positioning in the specs, so do not have spec files.
- DropdownButton: use `menu` 
- SplitButton: use `menu`
- HeaderBar App menu: use `menu`
- HeaderBar Profile menu: use `menu`

 docs(specs): components that requires positioning

---

cypress/integration/MultiSelect/Accepts_loading.feature
cypress/integration/MultiSelect/Can_be_opened_and_closed/index.js
cypress/integration/MultiSelect/common/index.js
cypress/integration/SingleSelect/Accepts_loading.feature
cypress/integration/SingleSelect/Can_be_opened_and_closed/index.js
cypress/integration/SingleSelect/common/index.js
src/MultiSelect.js
src/MultiSelect/Menu.js
src/MultiSelectOption.js
src/Select/FilterableMenu.js
src/Select/MenuWrapper.js
src/Select/option-helpers.js
src/SingleSelect.js
src/SingleSelect/Menu.js
src/SingleSelect/Selection.js
src/SingleSelectOption.js

This changes the behaviour of the loading spinner. When enabled, it'll be appended to the children, instead of replacing them. See this discussion: https://dhis2.slack.com/archives/CBM8LNEQM/p1577954451004500
It looks like this:
Todo:

feat(select): append loading spinner to children instead of replacing

---

src/__demo__/TextArea.stories.js

I assume this is not meant to be there, as the textarea has no required prop, but the textareafield does. Noticed this when I was checking the `required` stories.

docs: remove required textarea story

---

package.json

Fixed the issue where all "edit on github" links are broken.

docs: changed repository link in package.json to https

---

.github/workflows/cypress.yml
.github/workflows/node-test.yml

Running cypress and jest unit tests on push instead of pr, so that we run them on master as well.

ci(cypress): run tests on push instead of pr

---

cypress/drafts/Menu/position.feature
cypress/drafts/Popover/position.feature
cypress/drafts/Select/position.feature
cypress/drafts/Tooltip/position.feature
cypress/integration/Popper/Positions.feature
cypress/integration/Popper/Positions/index.js
cypress/support/getPositionsBySelectors.js
cypress/support/index.js
package.json
src/Popper.js
src/Popper/createPopper.js
src/__e2e__/Popper.stories.js
src/common-prop-types.js
yarn.lock

This branch will be used to collect feature files, changes to our components and possibly a positioning engine (ours or third party)
ToDos (added by @HendrikThePendric 23-01-2020):

refactor: positioning

---

src/Divider.js
src/Menu.js
src/MenuItem.js
src/MenuItem/styles.js
src/__demo__/Menu.stories.js

Fixes some of the issues from https://github.com/dhis2/ui-core/issues/500, I've not included things that could be considered features.
Fixed/Added to menu and/or menu-item
- min-width
- max-width, can be customised
- dense divider style
- destructive menu-item style
- disabled menu-item style
- allow multi-line menu items
- removed menu-item heights, now set via padding on content
- adjusted dense menu-item padding
I'm not sure if any of these would classify as being added as a `feat` instead, let me know if so.
Note: I've added and removed some props, I think I've done this in the correct way by documenting them with ` * @prop {boolean} [destructive]` etc. but an extra set of eyes here is much appreciated.

fix(menu): style adjustments, dense divider, multiline items

---

.storybook/decorators.js

This will add the jsx-addon decorator which is missing since we upgraded to the newer setup-style.

chore(storybook jsx addon): add missing decorator to show jsx again

---

src/Layer.js
src/__demo__/Layer.stories.js

- Start leveraging z-index stacking context
- Use `StackedLayer` to create a new stack/layer in the stacking context and append a portal to it
- Use `Layer` to append a portal to the current stacking context layer
- Use `BaseLayer` to append a portal to the document.body
---
I've been thinking about issue #596 and and have been experimenting with a possible solution for this. I think I have come up with the start of an approach that probably makes more sense than what we have now.
I think that at the core of the problem is the fact that our definition of how stacking should work in an app is an oversimplification of how things really work. Our [design specs](https://github.com/dhis2/design-system/blob/master/principles/spacing-alignment.md#stacking) only define 5 “layers” in an app, and …

refactor: improved layering system

---

src/Tooltip.js
src/__demo__/Tooltip.stories.js

The purpose of this PR is mainly to demonstrate a generic approach to dealing with components that need to be able to render any content, but do require this content to implement certain props. 
This is an example for the `Tooltip`, but we see the same/a very similar problem appear in  the `Menu`/`SubMenu` too.
The main idea is that we offer two methods of rendering:
- For default scenarios we accept children in the normal way (CONVENIENT)
- And if further customization is required we switch to the renderProps approach (FLEXIBLE)
So for the Tooltip this means:
- Normally children are simply wrapped in a `span` and the ref, OnMouseOver, onMouseOut props are attached to that in the Tooltip. If the app wants to use a different tag, this can be customised via the `tag` prop (see demo …

feat: tooltip with support for renderprops

---

src/MultiSelect/SelectionList.js

This PR changes the `Chip` type used in a `MultiSelect`. It adds a `dense` prop to the `Chip`.
Note: is this the correct conventional commit message type? It's not a `fix:` because this was not a bug, but is there something before `feat:`, more like...`adjustment: `? 😉

fix(MultiSelect): use dense chips for selections in input

---

src/Tooltip.js

Addresses a faulty propType noticed by @edoardo. See here for the related slack conversation: https://dhis2.slack.com/archives/CBM8LNEQM/p1588244299324200.

fix(tooltip): allow either function or node as children

---

cypress/integration/Popover/conditional_arrow/index.js
cypress/integration/Popover/position/index.js
package.json
src/Popover.js
src/Popover/Arrow.js
src/Popover/getArrowPosition.js
src/Popover/modifiers.js
src/Popper.js
src/Popper/modifiers.js
yarn.lock

This PR is essentially identical to https://github.com/dhis2/ui/pull/71 (apart from some import paths). Since @edoardo needs the popper fixed for patch release `2.34.1`, this needs to be implemented in ui-core too.
I guess the next steps should be something like this:
- Merge this into master once approved so a new minor version is released
- When we pull in the upstream (`@dhis2/ui-core`) changes to `@dhis2/ui`, we should fix the import paths and documentation links
- We can then close https://github.com/dhis2/ui/pull/71 because that will have become redundant/superseded...
- I'd also like to add some additional e2e test for arrow positions, I guess I can just add them later (in `@dhis2/ui`)

feat: let popper and popover accept react-refs or dom nodes directly
